# Numpy & Pandas Indexing.

In [1]:
import pandas as pd 
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [9]:
a=arr.reshape(3,3)

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a[[2,2],[0,2]]

array([7, 9])

In [46]:
a[[1,1],[0,2]]

array([4, 6])

In [50]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [51]:
type(a)


numpy.ndarray

In [52]:
np.ndim(a)

2

In [53]:
a.shape

(3, 3)

In [54]:
a.size

9

In [55]:
sum(a) 

array([12, 15, 18])

In [56]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a.Series()

AttributeError: 'numpy.ndarray' object has no attribute 'Series'

In [70]:
z=np.arange(1,31).reshape(5,6)

In [71]:
z

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [75]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [79]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
a[a<6]

array([1, 2, 3, 4, 5])

In [81]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
b=np.array([2,4,4,5,5,6,7,8,2.3])

In [85]:
b.reshape(3,3)

array([[2. , 4. , 4. ],
       [5. , 5. , 6. ],
       [7. , 8. , 2.3]])

In [87]:
np.unique(b)

array([2. , 2.3, 4. , 5. , 6. , 7. , 8. ])

In [90]:
set(list(b))

{2.0, 2.3, 4.0, 5.0, 6.0, 7.0, 8.0}

In [96]:
a=a.ravel()
a.reshape(2,-1)
a

ValueError: cannot reshape array of size 9 into shape (2,newaxis)

In [97]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a.reshape(2,-1)

ValueError: cannot reshape array of size 9 into shape (2,newaxis)

In [105]:
a=a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
c=pd.DataFrame(a)

In [104]:
c

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [113]:
c.iloc[1:,1:]

1  2
1  5  6
2  8  9

In [116]:
c.iloc[:2,:2]

0  1
0  1  2
1  4  5

In [111]:
c.iloc[0:2]

0  1  2
0  1  2  3
1  4  5  6

In [108]:
type(c)

pandas.core.frame.DataFrame

In [112]:
c.iloc[2,1:]

1    8
2    9
Name: 2, dtype: int32

In [117]:
c

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [144]:
d=pd.DataFrame(a,index=['index1','index2','index3'],columns=['col 1','col 2','col 3'])
d

col 1  col 2  col 3
index1      1      2      3
index2      4      5      6
index3      7      8      9

In [145]:
d.index=['I1','I2','I3']

In [146]:
d

col 1  col 2  col 3
I1      1      2      3
I2      4      5      6
I3      7      8      9

In [147]:
d.columns=['C1','C2','C3']

In [148]:
d

C1  C2  C3
I1   1   2   3
I2   4   5   6
I3   7   8   9

In [149]:
d.index=['I1','I2','I3']

In [150]:
d

C1  C2  C3
I1   1   2   3
I2   4   5   6
I3   7   8   9

In [151]:
d.iloc[1,1]

5

In [153]:
d.loc['I2':,'C2']

I2    5
I3    8
Name: C2, dtype: int32

In [155]:
d['C2']

I1    2
I2    5
I3    8
Name: C2, dtype: int32

In [156]:
d.loc[:,'C2']

I1    2
I2    5
I3    8
Name: C2, dtype: int32

In [162]:
d[['C2','C3']]

C2  C3
I1   2   3
I2   5   6
I3   8   9

In [163]:
d.C2   #d['C2']

I1    2
I2    5
I3    8
Name: C2, dtype: int32

In [164]:
df=pd.read_csv(r'C:\Users\Admin\Downloads\titanic train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [169]:
df.iloc[:6,:]


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q

In [170]:
df.shape

(891, 12)

In [172]:
df[['Name','Sex']]

Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
5                                     Moran, Mr. James    male
6                              McCarthy, Mr. Timothy J    male
7                       Palsson, Master. Gosta Leonard    male
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9                  Nasser, Mrs. Nicholas (Adele Achem)  female
10                     Sandstrom, Miss. Marguerite Rut  female
11                            Bonnell, Miss. Elizabeth  female
12                      Saundercock, Mr. William Henry    male
13                         Andersson, Mr. Anders Johan    male
14                Vestrom, Miss. Hulda Amanda Adolfina  female
15                    Hewlett, Mrs. (Mary D Kingcome)   female
16                                Rice, Master. Eugene    male
17                        Williams, Mr. Charles Eugene    male
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19                             Masselmani, Mrs. Fatima  female
20                                Fynney, Mr. Joseph J    male
21                               Beesley, Mr. Lawrence    male
22                         McGowan, Miss. Anna "Annie"  female
23                        Sloper, Mr. William Thompson    male
24                       Palsson, Miss. Torborg Danira  female
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female
26                             Emir, Mr. Farred Chehab    male
27                      Fortune, Mr. Charles Alexander    male
28                       O'Dwyer, Miss. Ellen "Nellie"  female
29                                 Todoroff, Mr. Lalio    male
..                                                 ...     ...
861                        Giles, Mr. Frederick Edward    male
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female
863                  Sage, Miss. Dorothy Edith "Dolly"  female
864                             Gill, Mr. John William    male
865                           Bystrom, Mrs. (Karolina)  female
866                       Duran y More, Miss. Asuncion  female
867               Roebling, Mr. Washington Augustus II    male
868                        van Melkebeke, Mr. Philemon    male
869                    Johnson, Master. Harold Theodor    male
870                                  Balkic, Mr. Cerin    male
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female
872                           Carlsson, Mr. Frans Olof    male
873                        Vander Cruyssen, Mr. Victor    male
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female
875                   Najib, Miss. Adele Kiamie "Jane"  female
876                      Gustafsson, Mr. Alfred Ossian    male
877                               Petroff, Mr. Nedelio    male
878                                 Laleff, Mr. Kristo    male
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female
880       Shelley, Mrs. William (Imanita Parrish Hall)  female
881                                 Markun, Mr. Johann    male
882                       Dahlberg, Miss. Gerda Ulrika  female
883                      Banfield, Mr. Frederick James    male
884                             Sutehall, Mr. Henry Jr    male
885               Rice, Mrs. William (Margaret Norton)  female
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [173]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
5                                       Moran, Mr. James
6                                McCarthy, Mr. Timothy J
7                         Palsson, Master. Gosta Leonard
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                    Nasser, Mrs. Nicholas (Adele Achem)
10                       Sandstrom, Miss. Marguerite Rut
11                              Bonnell, Miss. Elizabeth
12                        Saundercock, Mr. William Henry
13                           Andersson, Mr. Anders Johan
14                  Vestrom, Miss. Hulda Amanda Adolfina
15                      Hewlett, Mrs. (Mary D Kingcome) 
16                                  Rice, Master. Eugene
17                          Wil

In [174]:
df.iloc

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
5                                       Moran, Mr. James
6                                McCarthy, Mr. Timothy J
7                         Palsson, Master. Gosta Leonard
8      Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                    Nasser, Mrs. Nicholas (Adele Achem)
10                       Sandstrom, Miss. Marguerite Rut
11                              Bonnell, Miss. Elizabeth
12                        Saundercock, Mr. William Henry
13                           Andersson, Mr. Anders Johan
14                  Vestrom, Miss. Hulda Amanda Adolfina
15                      Hewlett, Mrs. (Mary D Kingcome) 
16                                  Rice, Master. Eugene
17                          Wil

In [175]:
df.iloc[:6,3:5]

Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                             Heikkinen, Miss. Laina  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                           Allen, Mr. William Henry    male
5                                   Moran, Mr. James    male

In [ ]:
# End...